image: node

stages:
  - test
  - build
  - deploy

compilação:
  stage: build

  artifacts:
    name: "$CI_JOB_NAME - $CI_COMMIT_REF_NAME"
    when: always
    paths:
      - ./website/build/test-site

  script:
    - cd website
    - npm install
    - npm run build