image: node

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - ./website/build

compilação:
  stage: build

  artifacts:
    name: "$CI_JOB_NAME - $CI_COMMIT_REF_NAME"
    when: always
    paths:
      - ./website/build/test-site

  script:
    - cd website
    - npm install
    - npm run build

deploy:
  stage: deploy

  script:
    - npm install -g surge
    - surge --project ./website/build/test-site --domain aloof-garden.surge.sh